jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Library Addresses
#####
- name: ERC165Utils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ERC165Utils]

- name: OldAgreementsAPI
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [AgreementsAPI]

#####
# Deploy new library implementation and register under a new version 1.2.0
#####

# Implementation
- name: NewAgreementsAPI
  deploy:
    contract: AgreementsAPI.bin
    libraries: ERC165Utils:$ERC165Utils

- name: registerAgreementsApiLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: registerVersion
    data: [AgreementsAPI, $NewAgreementsAPI, [1,2,0]]

- name: LookupAgreementsAPI
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [AgreementsAPI]

- name: AssertUpdatedAgreementsAPI
  assert:
    key: $LookupAgreementsAPI
    relation: eq
    val: $NewAgreementsAPI
