jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Library Addresses
#####
- name: ErrorsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ErrorsLib]

- name: ArrayUtilsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArrayUtilsLib]

- name: MappingsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [MappingsLib]

#####
# ArchetypeRegistry Upgrade
#####

- name: OldArchetypeRegistry
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArchetypeRegistry]

- name: NewArchetypeRegistry
  deploy:
    contract: DefaultArchetypeRegistry.bin
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib

- name: ChangeUpgradeOwnership
  call:
    destination: $NewArchetypeRegistry
    bin: UpgradeOwned
    function: transferUpgradeOwnership
    data: [$DOUG]

- name: DeployNewArchetypeRegistry
  call:
    destination: $DOUG
    bin: DOUG
    function: deploy
    data: ["ArchetypeRegistry", $NewArchetypeRegistry]

- name: AssertArchetypeRegistry
  assert:
    key: $DeployNewArchetypeRegistry
    relation: eq
    val: "true"

# Retrieve the updated repository via DOUG
- name: UpdatedArchetypeRegistry
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArchetypeRegistry]

- name: AssertUpdatedArchetypeRegistry
  assert:
    key: $UpdatedArchetypeRegistry
    relation: eq
    val: $NewArchetypeRegistry
