jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Library Addresses
#####
- name: ErrorsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ErrorsLib]

- name: TypeUtilsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [TypeUtilsLib]

- name: ArrayUtilsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArrayUtilsLib]

- name: MappingsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [MappingsLib]

- name: DataStorageUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [DataStorageUtils]

- name: ERC165Utils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ERC165Utils]

- name: AgreementsAPI
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [AgreementsAPI]

#####
# ActiveAgreement Upgrade
#####
- name: ActiveAgreementRegistry
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ActiveAgreementRegistry]

- name: ObjectClassActiveAgreement
  query-contract:
    destination: $ActiveAgreementRegistry
    bin: ActiveAgreementRegistry
    function: OBJECT_CLASS_AGREEMENT

- name: ActiveAgreementImplementationCurrentLookup
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [$ObjectClassActiveAgreement]

- name: ActiveAgreementVersionBeforeUpgrade
  query-contract:
    destination: $ActiveAgreementImplementationCurrentLookup
    bin: ActiveAgreement
    function: getArtifactVersion

- name: ActiveAgreementImplementationUpgrade
  deploy:
    contract: DefaultActiveAgreement.bin
    libraries: ErrorsLib:$ErrorsLib, TypeUtilsLib:$TypeUtilsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib, DataStorageUtils:$DataStorageUtils, AgreementsAPI:$AgreementsAPI, ERC165Utils:$ERC165Utils

- name: RegisterActiveAgreementObjectClass
  call:
    destination: $DOUG
    bin: DOUG
    function: register
    data: [$ObjectClassActiveAgreement, $ActiveAgreementImplementationUpgrade]

- name: ActiveAgreementImplementationUpgradeLookup
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [$ObjectClassActiveAgreement]

- name: ActiveAgreementVersionAfterUpgrade
  query-contract:
    destination: $ActiveAgreementImplementationUpgradeLookup
    bin: ActiveAgreement
    function: getArtifactVersion

- name: AssertActiveAgreementUpgradeRegistered
  assert:
    key: $ActiveAgreementImplementationUpgradeLookup
    relation: eq
    val: $ActiveAgreementImplementationUpgrade
