jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Library Addresses
#####
- name: ErrorsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookupContract
    data: [ErrorsLib]

- name: TypeUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookupContract
    data: [TypeUtils]

- name: ArrayUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookupContract
    data: [ArrayUtils]

- name: MappingsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookupContract
    data: [MappingsLib]

- name: BpmModelLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookupContract
    data: [BpmModelLib]

- name: DataStorageUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookupContract
    data: [DataStorageUtils]

#####
# ProcessModelRepository (old)
#####
- name: OldProcessModelRepository
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookupContract
    data: [ProcessModelRepository]

- name: OldProcessModelRepositoryVersion
  query-contract:
    destination: $OldProcessModelRepository
    bin: ProcessModelRepository
    function: getVersion

- name: OldProcessModelRepositoryNumberOfModels
  query-contract:
    destination: $OldProcessModelRepository
    bin: ProcessModelRepository
    function: getNumberOfModels

#####
# ProcessModelRepository (new)
######
- name: NewProcessModelRepository
  deploy:
    contract: DefaultProcessModelRepository.bin
    libraries: ErrorsLib:$ErrorsLib, TypeUtilsAPI:$TypeUtils, ArrayUtilsAPI:$ArrayUtils, MappingsLib:$MappingsLib, BpmModelLib:$BpmModelLib, DataStorageUtils:$DataStorageUtils

- name: ChangeRepositoryUpgradeOwnership
  call:
    destination: $NewProcessModelRepository
    bin: UpgradeOwned
    function: transferUpgradeOwnership
    data: [$DOUG]

- name: DeployNewProcessModelRepository
  call:
    destination: $DOUG
    bin: DOUG
    function: deployContract
    data: [ProcessModelRepository, $NewProcessModelRepository]

- name: AssertProcessModelRepositoryUpgradeSuccess
  assert:
    key: $DeployNewProcessModelRepository
    relation: eq
    val: "true"

- name: NewProcessModelRepositoryVersion
  query-contract:
    destination: $NewProcessModelRepository
    bin: ProcessModelRepository
    function: getVersion

- name: NewProcessModelRepositoryNumberOfModels
  query-contract:
    destination: $NewProcessModelRepository
    bin: ProcessModelRepository
    function: getNumberOfModels

- name: AssertProcessModelRepositoryUpgradeSize
  assert:
    key: $NewProcessModelRepositoryNumberOfModels
    relation: eq
    val: $OldProcessModelRepositoryNumberOfModels
