version: 2.1
jobs:
  swagger:
    docker:
    - image: quay.io/goswagger/swagger
    steps:
      - checkout
      - run: apk add --update nodejs nodejs-npm
      - run: npm config set unsafe-perm true
      - run: npm install swagger-jsdoc -g
      - run: make swaggerize
      - run: |
          if [ ! -z "$(git status --porcelain)" ];
          then
            echo "Uncommitted swagger changes.";
          fi

  test:
    machine: &machine_defaults
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - &add_ssh_key
        add_ssh_keys:
          fingerprints:
            - "5e:f3:47:75:34:c7:83:93:51:48:31:6a:3a:1a:de:85"
      - checkout
      - run: make docker_test
      - store_artifacts:
          path: ./test/docker-compose.log

  deploy_docs:
    docker:
    - image: quay.io/monax/blackstone:ci
    steps:
      - <<: *add_ssh_key
      - checkout
      - run: make build_contracts
      - run: make push_docs

workflows:
  test_and_deploy:
    jobs:
      - swagger
      - test
      - deploy_docs:
          filters:
            branches:
              only:
                - master
