defaults: &defaults
  docker:
    - image: quay.io/monax/build:latest
  working_directory: ~/blackstone
  environment:
    IMAGE_API: quay.io/monax/blackstone

version: 2
jobs:

  cache_contracts:
    <<: *defaults
    steps:
      - checkout
      - run: burrow deploy --file build.yaml --dir ./contracts/src
      - persist_to_workspace:
          root: ./contracts/src/
          paths:
            - bin

  cache_api:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - api-{{ checksum "api/package-lock.json" }}
            - api
      - run:
          name: Install npm
          command: |
            cd ./api/
            npm install
      - save_cache:
          key: api-{{ checksum "api/package-lock.json" }}
          paths:
            - api/node_modules/
      - persist_to_workspace:
          root: ./api/
          paths:
            - node_modules

  test_contracts:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: contracts/src
      - run: ./test/test_contracts.sh
      - store_artifacts:
          path: ./burrow.log
      - store_artifacts:
          path: ./test-contracts-jobs.log
      - store_artifacts:
          path: ./test-contracts.log

  test_api:
    docker:
      - image: quay.io/monax/build:latest
      - image: quay.io/monax/hoard:1.1.3
        name: hoard
      - image: postgres:9-alpine
        name: postgres
        environment:
          POSTGRES_USER: blackstone_development
          POSTGRES_PASSWORD: blackstone_development
    working_directory: ~/blackstone
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: |
          mv /tmp/bin ./contracts/src/.
          mv /tmp/node_modules ./api/.
      - run: ./test/test_api.sh
      - store_artifacts:
          path: ./burrow.log

  deploy_docs:
    <<: *defaults
    steps:
      - checkout
      - run: ./docs/generate.sh

  deploy_platform:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Trigger upgrade
          command: |
            set -x
            curl \
              --request POST \
              --form token=$PLATFORM_DEPLOY_KEY \
              --form ref=master \
              --form "variables[BUILD_REFSPEC]=$CIRCLE_BRANCH" \
              $PLATFORM_DEPLOY_URL/trigger/pipeline

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - cache_contracts:
          filters:
            branches:
              ignore: master
      - cache_api:
          filters:
            branches:
              ignore: master
      - test_contracts:
          requires:
            - cache_contracts
          filters:
            branches:
              ignore: master
      - test_api:
          requires:
            - cache_api
            - cache_contracts
          filters:
            branches:
              ignore: master
      - deploy_docs:
          filters:
            branches:
              only:
                - master
      - deploy_platform:
          filters:
            branches:
              only:
                - master
                - develop
