version: 2.1
jobs:

  test:
    machine: &machine_defaults
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: make test
      - persist_to_workspace:
          root: ./contracts/src/
          paths:
            - bin
      - store_artifacts:
          path: ./test/chain/burrow.log
      - store_artifacts:
          path: ./test-contracts-jobs.log
      - store_artifacts:
          path: ./test-contracts.log

  deploy_docs:
    docker:
    - image: node:11-alpine
    steps:
      - checkout
      - &add_ssh_key
        add_ssh_keys:
          fingerprints:
            - "5e:f3:47:75:34:c7:83:93:51:48:31:6a:3a:1a:de:85"
      - run: ./docs/generate.sh

  update_info:
    docker:
      - image: alpine/git
    environment:
      CHAIN_INFO: "t5"
      CHAIN_INFO_HOST: "info.agreements.network"
    steps:
      - checkout
      - <<: *add_ssh_key
      - attach_workspace:
          at: /tmp
      - run: ./scripts/update_info.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_docs:
          filters:
            branches:
              only:
                - master
      - update_info:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
