defaults: &defaults
  docker:
    - image: quay.io/monax/build:latest
  working_directory: ~/blackstone
  environment:
    IMAGE_API: quay.io/monax/blackstone

version: 2.1
jobs:
  test:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: make install_api
      - run: make test
      - store_artifacts:
          path: ./test/chain/burrow.log
      - store_artifacts:
          path: ./test-contracts-jobs.log
      - store_artifacts:
          path: ./test-contracts.log

  deploy_docs:
    <<: *defaults
    steps:
      - checkout
      - &add_ssh_key
        add_ssh_keys:
          fingerprints:
            - "5e:f3:47:75:34:c7:83:93:51:48:31:6a:3a:1a:de:85"
      - run: ./docs/generate.sh

  deploy_platform:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Trigger upgrade
          command: |
            set -x
            curl \
              --request POST \
              --form token=$PLATFORM_DEPLOY_KEY \
              --form ref=master \
              $PLATFORM_DEPLOY_URL

  update_info:
    docker:
      - image: alpine/git
    environment:
      CHAIN_INFO: "t5"
      CHAIN_INFO_HOST: "info.agreements.network"
    steps:
      - checkout
      - <<: *add_ssh_key
      - attach_workspace:
          at: /tmp
      - run:
          name: "Update AN Info"
          command: |
            if [ $CIRCLE_BRANCH != "master" ]; then CHAIN_INFO="${CHAIN_INFO}-dev"; fi
            CHAIN_OUT_DIR="${CHAIN_INFO_HOST}/${CHAIN_INFO}"
            CHAIN_INFO_URL="https://${CHAIN_INFO_HOST}/${CHAIN_INFO}"
            git config --global user.name "Billings, a Bot"
            git config --global user.email "billings@monax.io"
            git clone git@github.com:agreements-network/info $CHAIN_INFO_HOST
            mkdir -p ${CHAIN_OUT_DIR}/abi
            mkdir -p ${CHAIN_OUT_DIR}/specs
            while read -r abi; do
              echo "${CHAIN_INFO_URL}/abi/${abi}.bin" >> ${CHAIN_OUT_DIR}/abi-new.csv
              cp /tmp/bin/${abi}.bin ${CHAIN_OUT_DIR}/abi/.
            done < ./contracts/abi.csv
            mv ${CHAIN_OUT_DIR}/abi-new.csv ${CHAIN_OUT_DIR}/abi.csv
            for spec in ./api/sqlsol/*; do
              echo "${CHAIN_INFO_URL}/specs/$(basename ${spec})" >> ${CHAIN_OUT_DIR}/spec-new.csv
              cp $spec ${CHAIN_OUT_DIR}/specs/.
            done
            mv ${CHAIN_OUT_DIR}/spec-new.csv ${CHAIN_OUT_DIR}/spec.csv
            cd ${CHAIN_INFO_HOST}
            git add -A :/
            git commit -m "Automatic info generation from AN build on `date`" || true
            git push
            sleep 60 # allow time for GH pages to render

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_docs:
          filters:
            branches:
              only:
                - master
      - update_info:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - deploy_platform:
          requires:
            - test
            - update_info
          filters:
            branches:
              only:
                - master
                - develop
