# burrow deploy -f $FILE -a $ADDR -e piAddress=$PROCESS_INSTANCE_ADDRESS
jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Oracle Address
#####
- name: WaitOracle
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: ["WaitOracle"]

- name: WaitOracleActivator
  deploy:
    contract: WaitOracleActivator.sol
    data: [$WaitOracle]

#####
# Tickle Oracle
#####
- name: triggerOracleInProcessInstance
  call:
    destination: $WaitOracleActivator
    bin: WaitOracleActivator
    function: triggerOracleInProcessInstance
    data: [$piAddress]
