identity_provider = "TEST_ECOSYSTEM" # for testing/demo only. This should be overwritten using the ENV var IDENTITY_PROVIDER

hoard = "hoard:53431"
analyticsID = "TEST"

[server]
#port_http =               # default: 3080
#port_https =              # default: 3443
#context_path =            # default: 'portal'
#upload_limit =        # default: '100mb'

[chain]
host = "chain"
port = 10997

[accounts]
server = "0201EF325305ABD75E1FB8A8F539730F71547484"     # for testing/demo only! The account address to use for signing. ENV var ACCOUNTS_SERVER_KEY overwrites this, if set!

[contracts]
load = "EcosystemRegistry, ParticipantsManager, ArchetypeRegistry, ActiveAgreementRegistry, ProcessModelRepository, ApplicationRegistry, BpmService"

[jwt]
issuer = "Agreements.Network"
expiresIn = "1h"
secret = "s3cr3t"

[cookie]
name = "access_token"
maxAge = 3600000 # milliseconds
httpOnly = true
