jobs:
  - name: ErrorsLib
    build:
      contract: commons-base/ErrorsLib.sol
  - name: TypeUtilsLib
    build:
      contract: commons-utils/TypeUtilsLib.sol
  - name: ArrayUtilsLib
    build:
      contract: commons-utils/ArrayUtilsLib.sol
  - name: MappingsLib
    build:
      contract: commons-collections/MappingsLib.sol
  - name: DefaultProcessModelRepository
    build:
      contract: bpm-model/DefaultProcessModelRepository.sol
  - name: ProcessModelRepositoryDb
    build:
      contract: bpm-model/ProcessModelRepositoryDb.sol
  - name: ProcessModelInterface
    build:
      contract: bpm-model/ProcessModel.sol
  - name: ProcessModelRepositoryTest
    build:
      contract: bpm-model/test/ProcessModelRepositoryTest.sol
  - name: ProcessModelTest
    build:
      contract: bpm-model/test/ProcessModelTest.sol
  - name: ProcessDefinitionTest
    build:
      contract: bpm-model/test/ProcessDefinitionTest.sol
      instance: ProcessDefinitionTest
