
##########
# Libraries
jobs:

- name: TypeUtilsLib
  deploy:
    contract: TypeUtilsLib.bin

- name: ArrayUtilsLib
  deploy:
    contract: ArrayUtilsLib.bin

- name: MappingsLib
  deploy:
    contract: MappingsLib.bin
    libraries: TypeUtilsLib:$TypeUtilsLib, ArrayUtilsLib:$ArrayUtilsLib

#####
# PubSub Test
#####
- name: PubSubTest
  deploy:
    contract: PubSubTest.bin
    instance: PubSubTest
    libraries: MappingsLib:$MappingsLib

- name: runPubSubTest
  call:
    destination: $PubSubTest
    bin: PubSubTest
    function: testPubSub

- name: assertPubSubTest
  assert:
    key: $runPubSubTest
    relation: eq
    val: success
