jobs:

- name: ErrorsLib
  deploy:
    contract: ErrorsLib.bin

- name: ERC165Utils
  deploy:
    contract: ERC165Utils.bin

- name: AgreementsAPI
  deploy:
    contract: AgreementsAPI.bin
    libraries: ERC165Utils:$ERC165Utils

- name: Strings
  deploy:
    contract: Strings.bin

- name: DateRelationsTest
  deploy:
    contract: agreements/test/DateRelationsTest.sol
    libraries: AgreementsAPI:$AgreementsAPI, Strings:$Strings, ErrorsLib:$ErrorsLib

- name: testDateRelations
  call:
    destination: $DateRelationsTest
    function: testDateRelations

- name: assertDateRelations
  assert:
    key: $testDateRelations
    relation: eq
    val: success
