jobs:

- name: ErrorsLib
  deploy:
    contract: ErrorsLib.bin

- name: ERC165Utils
  deploy:
    contract: ERC165Utils.bin

- name: AgreementsAPI
  deploy:
    contract: AgreementsAPI.bin
    libraries: ERC165Utils:$ERC165Utils

- name: Strings
  deploy:
    contract: Strings.bin

- name: CompletablesTest
  deploy:
    contract: agreements/test/CompletablesTest.sol
    libraries: AgreementsAPI:$AgreementsAPI, Strings:$Strings, ErrorsLib:$ErrorsLib

- name: testCompletables
  call:
    destination: $CompletablesTest
    function: testCompletables

- name: assertCompletables
  assert:
    key: $testCompletables
    relation: eq
    val: success
