name: test
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  mocha:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: actions/checkout@v2
    - run: make docker_run_chain
    - run: yarn install
    - run: yarn test

  solidity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make docker_test_chain
